import { createFileRoute } from "@tanstack/react-router";
import { Link2, Shield, SlidersHorizontal, User } from "lucide-react";
import { DashboardPage, PageHero } from "@/components/dashboard/page-kit";
import { Switch } from "@/components/ui/switch";
export const Route = createFileRoute("/_authenticated/settings")({ head: () => ({ meta: [{ title: "Settings — ScrollMiles" }] }), component: SettingsPage });
function SettingsPage(){return <DashboardPage>{(data)=>{const p=data.profile??{};return <><PageHero eyebrow="Settings" title="Control your ScrollMiles experience" body="Manage profile settings, data permissions, Google account status, and privacy controls from one responsive page."/><div className="grid lg:grid-cols-2 gap-6"><Panel icon={<User/>} title="Profile settings"><Field label="Display name" value={p.display_name??"ScrollMiles User"}/><Field label="Email" value={p.email??"Connected account"}/><Field label="Data source" value={p.data_source??"estimated"}/></Panel><Panel icon={<Shield/>} title="Data permissions"><Toggle label="Browser analytics" checked/><Toggle label="Device usage sync" checked={p.data_source==="verified"}/><Toggle label="AI insight generation" checked/></Panel><Panel icon={<Link2/>} title="Google account"><Field label="Status" value="Connected securely with Supabase Auth"/><Field label="Sync" value="Profile and avatar sync enabled"/><button className="mt-4 h-10 px-4 rounded-xl border border-border text-sm font-semibold hover:bg-muted transition">Reconnect Google</button></Panel><Panel icon={<SlidersHorizontal/>} title="Privacy controls"><Toggle label="Hide ingestion tokens" checked/><Toggle label="Keep reports private" checked/><Toggle label="Allow anonymized product analytics" checked={false}/></Panel></div></>}}</DashboardPage>}
function Panel({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <section className="rounded-3xl bg-card border border-border p-6 shadow-soft"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-gradient-soft grid place-items-center text-purple-500">{icon}</div><h2 className="text-xl font-bold">{title}</h2></div><div className="mt-5 space-y-4">{children}</div></section>}
function Field({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-border bg-background p-4"><div className="text-xs uppercase tracking-widest text-muted-foreground font-semibold">{label}</div><div className="mt-1 font-medium break-words">{value}</div></div>}
function Toggle({label,checked}:{label:string;checked:boolean}){return <div className="flex items-center justify-between rounded-2xl border border-border bg-background p-4"><span className="font-medium">{label}</span><Switch checked={checked} aria-label={label}/></div>}
