/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'

const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedAchievementsRoute = AuthenticatedAchievementsRouteImport.update({ id: '/achievements', path: '/achievements', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({ id: '/activity', path: '/activity', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({ id: '/analytics', path: '/analytics', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({ id: '/reports', path: '/reports', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => AuthenticatedRouteRoute } as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({ id: '/api/public/ingest', path: '/api/public/ingest', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/achievements' | '/activity' | '/analytics' | '/dashboard' | '/reports' | '/settings' | '/api/public/ingest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/achievements' | '/activity' | '/analytics' | '/dashboard' | '/reports' | '/settings' | '/api/public/ingest'
  id: '__root__' | '/' | '/_authenticated' | '/auth' | '/_authenticated/achievements' | '/_authenticated/activity' | '/_authenticated/analytics' | '/_authenticated/dashboard' | '/_authenticated/reports' | '/_authenticated/settings' | '/api/public/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren { IndexRoute: typeof IndexRoute; AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren; AuthRoute: typeof AuthRoute; ApiPublicIngestRoute: typeof ApiPublicIngestRoute }

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated': { id: '/_authenticated'; path: ''; fullPath: '/'; preLoaderRoute: typeof AuthenticatedRouteRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/achievements': { id: '/_authenticated/achievements'; path: '/achievements'; fullPath: '/achievements'; preLoaderRoute: typeof AuthenticatedAchievementsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/activity': { id: '/_authenticated/activity'; path: '/activity'; fullPath: '/activity'; preLoaderRoute: typeof AuthenticatedActivityRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/analytics': { id: '/_authenticated/analytics'; path: '/analytics'; fullPath: '/analytics'; preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/dashboard': { id: '/_authenticated/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof AuthenticatedDashboardRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/reports': { id: '/_authenticated/reports'; path: '/reports'; fullPath: '/reports'; preLoaderRoute: typeof AuthenticatedReportsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/settings': { id: '/_authenticated/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof AuthenticatedSettingsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/api/public/ingest': { id: '/api/public/ingest'; path: '/api/public/ingest'; fullPath: '/api/public/ingest'; preLoaderRoute: typeof ApiPublicIngestRouteImport; parentRoute: typeof rootRouteImport }
  }
}

interface AuthenticatedRouteRouteChildren { AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute; AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute; AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute; AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute; AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute; AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute }
const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = { AuthenticatedAchievementsRoute, AuthenticatedActivityRoute, AuthenticatedAnalyticsRoute, AuthenticatedDashboardRoute, AuthenticatedReportsRoute, AuthenticatedSettingsRoute }
const AuthenticatedRouteRouteWithChildren = AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)
const rootRouteChildren: RootRouteChildren = { IndexRoute, AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren, AuthRoute, ApiPublicIngestRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
